### ISSUE TITLE
Update bower registry and make rowGrid available in npm registry

### ISSUE THREAD

**Issue by piotrd** [brunjo/rowGrid.js#22]
Hi,

Would you mind making rowGrid available in npm registry, please?

Also, bower registry reports version 1.0.3 being current, while there is 1.0.4 available. Can you please update that, too?

**Comment by brunjo** [comment]
It's now also on npm: https://www.npmjs.com/package/rowgrid.js.

If I run `bower install rowGrid.js` I get the newest version!?

**Comment by piotrd** [comment]
> It's now also on npm: https://www.npmjs.com/package/rowgrid.js.

Thanks for prompt action! 

> If I run bower install rowGrid.js I get the newest version!?

Sorry, my bad, I took a look at https://libraries.io/bower/rowGrid.js where for some reason there is 1.0.3 listed as the latest version.
