### ISSUE TITLE
Resize fails in Safari (9.1 Mac)

### ISSUE THREAD

**Issue by dgsjm** [brunjo/rowGrid.js#24]
Safari 9.1 for Mac does not seem to "Resize" the grid correctly.
When I shrink the browser horizontally, the grid falls apart.
When I enlarge the browser horizontally, the grid aligns correctly again.

The "resize" event is fired and the "layout" function is called, but the grid has many holes.
I have included a screenshot using the provided demo.

![image](https://cloud.githubusercontent.com/assets/4389957/15054067/81728234-12ba-11e6-84e3-be8b0bb23817.png)

Edit:
I had some success by adding a delay (and "throttle") to the "layout" call. The images flicker a bit on resize due to the delay, but the grid remains intact. I'd still love to figure out why Safari does this and whether there's a better solution.

**Comment by brunjo** [comment]
This bug only occurred when you set "Show scrollbars" in the general preferences of your Mac to "Always".

I fixed it by adding `overflow-y: scroll;` to the `html` or `body` tag`. You can try it at http://brunjo.github.io/rowGrid.js/. It should be fixed now.

**Comment by dgsjm** [comment]
Thanks, Brunjo. Your CSS adjustment seems to work great. Much appreciated.

**Comment by MNKH** [comment]
I have almost the same problem. Only after resize is displayed.
http://take.ms/g1IIo

**Comment by brunjo** [comment]
@MNKH You should make sure that you either wait until all images are loaded and then call the `rowGrid` method or add `width` and `height` attributes to your images.
