### ISSUE TITLE
Just a litter bug

### ISSUE THREAD

**Issue by leehave** [brunjo/rowGrid.js#28]
Excuse me , there was something wrong with the http://139.129.207.146/index.php?r=resource%2Fgallery . Thanks for you if you

**Comment by leehave** [comment]
If you have multiple refresh dislocation will appear unable to load or pictures

**Comment by brunjo** [comment]
Is the issue resolved? If not, could you give a minimal example where this bug occurs. And did you already tried this: https://github.com/brunjo/rowGrid.js/issues/27#issuecomment-237821066?
