### ISSUE TITLE
Sometimes i get width: 0px.

### ISSUE THREAD

**Issue by febyolaaldo** [brunjo/rowGrid.js#34]
When i try to reload again, everything is running well. But, when i try to clear cache, i get width: 0px again. What can i do?
![image](https://user-images.githubusercontent.com/14918616/39520557-4fbdc308-4e35-11e8-80c3-ed76175aa7bb.png)

**Comment by brunjo** [comment]
I guess the images inside the `figure` element aren't loaded yet. You should make sure you call rowGrid only after all images are loaded. Alternatively, you could add the width and height of the images as attributes to the `img` elements like this: `<img src="…" width="200" height="160"`

**Comment by febyolaaldo** [comment]
yeah, fixed with setTimeout function.
Thanks @brunjo
